<?php

namespace Drupal\dyniva_matomo\Plugin\Block;

use Drupal\Core\Form\FormStateInterface;

/**
 * Matomo visits page rank.
 *
 * @Block(
 *  id = "dyniva_matomo_pages",
 *  admin_label = @Translation("Matomo visits page rank"),
 * )
 */
class Pages extends MatomoWidgetBase {

  /**
   * {@inheritDoc}
   */
  public function getContent() {
    return [];
  }

  /**
   * {@inheritDoc}
   */
  public function getApiCallback() {
    return $this->configuration['api_callback'];
  }

  /**
   * {@inheritDoc}
   */
  public function getApiParams() {
    $params = [
      'expanded' => 1,
      'flat' => 1,
      'filter_limit' => $this->configuration['filter_limit'],
      'filter_sort_column' => $this->configuration['filter_sort_column'],
    ];
    if (!empty($this->configuration['date'])) {
      $params['date'] = $this->configuration['date'];
    }
    if (!empty($this->configuration['period'])) {
      $params['period'] = $this->configuration['period'];
    }
    return $params;
  }

  /**
   * {@inheritDoc}
   */
  public function getApiMethod() {
    return $this->configuration['api_method'];
  }

  /**
   *
   * {@inheritDoc}
   * @see \Drupal\Core\Block\BlockBase::blockForm()
   */
  public function blockForm($form, FormStateInterface $form_state) {
    $form = parent::blockForm($form, $form_state);
    $form['filter_limit'] = array(
      '#title' => t('Rows limit'),
      '#type' => 'number',
      '#max' => 50,
      '#default_value' => !empty($this->configuration['filter_limit']) ? $this->configuration['filter_limit'] : 10,
    );
    return $form;
  }

  /**
   *
   * {@inheritDoc}
   * @see \Drupal\dyniva_matomo\Plugin\Block\MatomoWidgetBase::blockSubmit()
   */
  public function blockSubmit($form, FormStateInterface $form_state) {
    parent::blockSubmit($form, $form_state);
    $this->setConfigurationValue('filter_limit', $form_state->getValue('filter_limit'));
  }

  /**
   * {@inheritDoc}
   */
  public function defaultConfiguration() {
    return [
      'api_callback' => 'dyniva_matomo_pages_api_callback',
      'api_method' => 'Actions.getPageUrls',
      'period' => 'day',
      'filter_limit' => 50,
      'filter_sort_column' => 'nb_hits',
      'total' => FALSE,
      'visit_log' => FALSE,
      'evolution' => FALSE,
    ];
  }

  /**
   * {@inheritDoc}
   */
  public function build() {
    $build = parent::build(); // TODO: Change the autogenerated stub
    $build['#content']['id'] = $this->getWidgetId();
    $build['#content']['method'] = $this->configuration['api_method'];
    $build['#content']['total'] = $this->configuration['total'];
    $build['#content']['method'] = $this->configuration['api_method'];
    $build['#content']['visit_log'] = $this->configuration['visit_log'];
    $build['#content']['evolution'] = $this->configuration['evolution'];

    $build['#content']['image_base_path'] = \Drupal::request()->getBasePath() . '/' . drupal_get_path('module', 'dyniva_matomo') . '/icons/';;
    $build['#theme'] = 'dyniva_matomo_pages';
    $build['#attached']['library'][] = 'dyniva_admin/echarts';

    return $build;
  }
}
